### ISSUE TITLE
It doesn't work with the Python API: AssertionError: Torch not compiled with CUDA enabled

### ISSUE THREAD

**Issue by hdnh2006** [deepconsc/tensorrt_yolov5#2]
Hello!

Thanks for this fantastic repo, have you checked the python API?

I tried on my jetson the following command:
`python inference.py`

And I got this error:
`AssertionError: Torch not compiled with CUDA enabled`

So I decided to go step by step and when it tries to load de "`yolov5.engine`" I get the error. These are the lines of code I ran on my Jetson:
```
python
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
import glob 
import cv2 
import time 
import tqdm

import numpy as np 
from yolov5s import YoLov5TRT
images = glob.glob('sample_images/*.jpg')
yolo = YoLov5TRT(checkpoint_path='build/yolov5s.engine', device_num=0)
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +198, GPU +0, now: CPU 269, GPU 2566 (MiB)
[TensorRT] INFO: Loaded engine size: 21 MB
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine begin: CPU 290 MiB, GPU 2608 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +155, GPU +153, now: CPU 455, GPU 2776 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +240, GPU +239, now: CPU 695, GPU 3015 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 695, GPU 3015 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] deserializeCudaEngine end: CPU 695 MiB, GPU 3015 MiB
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation begin: CPU 673 MiB, GPU 2994 MiB
[TensorRT] INFO: [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +1, GPU +0, now: CPU 674, GPU 2994 (MiB)
[TensorRT] INFO: [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 674, GPU 2994 (MiB)
[TensorRT] INFO: [MemUsageSnapshot] ExecutionContext creation end: CPU 674 MiB, GPU 2994 MiB
  0%|                                                                                                                                                                               | 0/20 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/henry/Projects/deepconsc/yolov5_conversion/tensorrt_yolov5/yolov5s.py", line 74, in __init__
    self.warmup()
  File "/home/henry/Projects/deepconsc/yolov5_conversion/tensorrt_yolov5/yolov5s.py", line 83, in warmup
    self.infer((standard + 255).astype(np.uint8))
  File "/home/henry/Projects/deepconsc/yolov5_conversion/tensorrt_yolov5/yolov5s.py", line 127, in infer
    output[i * 6001: (i + 1) * 6001], batch_origin_h[i], batch_origin_w[i]
  File "/home/henry/Projects/deepconsc/yolov5_conversion/tensorrt_yolov5/yolov5s.py", line 200, in postprocess
    pred = torch.Tensor(pred).cuda()
  File "/home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages/torch/cuda/__init__.py", line 166, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled
```

If I run the code with `sudo ./yolov5 -d yolov5s.engine ../sample_images` it goes well.

I hope this information can help you to improve this repo.

**Comment by hdnh2006** [comment]
It seems `torch` and `torchvision` have to be compiled from source using the following steps:
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048

The problem I am getting right now is I use virtualenv for almost everything and despite I was working in my virtualenv, torchvision was installed in the "general" `site-packages` as it is seen in the logs:


```
... (A lot of logs and time passed after this)
creating dist
creating 'dist/torchvision-0.10.0-py3.6-linux-aarch64.egg' and adding 'build/bdist.linux-aarch64/egg' to it
removing 'build/bdist.linux-aarch64/egg' (and everything under it)
Processing torchvision-0.10.0-py3.6-linux-aarch64.egg
creating /home/henry/.local/lib/python3.6/site-packages/torchvision-0.10.0-py3.6-linux-aarch64.egg
Extracting torchvision-0.10.0-py3.6-linux-aarch64.egg to /home/henry/.local/lib/python3.6/site-packages

**Installed /home/henry/.local/lib/python3.6/site-packages/torchvision-0.10.0-py3.6-linux-aarch64.egg**
Processing dependencies for torchvision==0.10.0
Searching for Pillow==8.3.2
Best match: Pillow 8.3.2

Using /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages
Searching for torch==1.9.0
Best match: torch 1.9.0
Installing convert-caffe2-to-onnx script to /home/henry/.local/bin
Installing convert-onnx-to-caffe2 script to /home/henry/.local/bin

Using /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages
Searching for numpy==1.19.5
Best match: numpy 1.19.5
Installing f2py script to /home/henry/.local/bin
Installing f2py3 script to /home/henry/.local/bin
Installing f2py3.6 script to /home/henry/.local/bin

Using /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages
Searching for typing-extensions==3.10.0.2
Best match: typing-extensions 3.10.0.2

Using /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages
Searching for dataclasses==0.8
Best match: dataclasses 0.8

Using /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages
```

However after deactivate my virtualenv, I couldn't import torchvision, so I don't know what is happening now.
```
python3
Python 3.6.9 (default, Jan 26 2021, 15:33:00) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torchvision
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torchvision'
```

I will try it again the next week. Sorry.

**Comment by deepconsc** [comment]
Hey @hdnh2006!

The possible reason behind the issue might be cached torch[vision] versions that are accessible via python. 
As I've seen some people are having issues with running the entire repo when they don't use base Jetpack images. Alternative installations sometimes break the codebase. 

```
bash requirements.sh
```
Installs all the required dependencies along with torch & torchvision, starting from **_[line 14](https://github.com/deepconsc/tensorrt_yolov5/blob/master/requirements.sh#L14)_**

I'll try to replicate the error in following days. 
Based on GPU VRAM I'd say you're using Nano?

**Comment by hdnh2006** [comment]
Thanks @deepconsc for the quick reply.

Yes, I am trying to use your code in the Jetson Nano and I think this is the problem I had. According to the NVIDIA forum ([link](https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-9-0-now-available/72048)), it is neccesary to install the specific version of Pytorch for Jetson Nano. I guess you do that in the [requirements.sh](https://github.com/deepconsc/tensorrt_yolov5/blob/a402b917b8dc6ad2f7216f3ef5a1024db54d29fe/requirements.sh) file from lines https://github.com/deepconsc/tensorrt_yolov5/blob/a402b917b8dc6ad2f7216f3ef5a1024db54d29fe/requirements.sh#L14 to https://github.com/deepconsc/tensorrt_yolov5/blob/a402b917b8dc6ad2f7216f3ef5a1024db54d29fe/requirements.sh#L19. 

However, it seems this doesn't work if you are working with virtual environments, because torchvision is being installed again in the requirements.txt file https://github.com/deepconsc/tensorrt_yolov5/blob/a402b917b8dc6ad2f7216f3ef5a1024db54d29fe/requirements.txt#L5 . And here is where I think I am having a package problem.

So, what I did was comment some lines of the `requeriments.sh`, specifically those related with torch and torch vision installation and I ran the next lines, following the instructions of the Nvidia forum:

```
# For Torch
wget https://nvidia.box.com/shared/static/h1z9sw4bb1ybi0rm3tu8qdj8hs05ljbm.whl -O torch-1.9.0-cp36-cp36m-linux_aarch64.whl 
sudo apt-get install python3-pip libopenblas-base libopenmpi-dev 
pip3 install Cython
pip3 install numpy torch-1.9.0-cp36-cp36m-linux_aarch64.whl 

# And then for torchvision
sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
git clone --branch v0.10.0 https://github.com/pytorch/vision torchvision   # see below for version of torchvision to download
cd torchvision
export BUILD_VERSION=0.10.0  # where 0.x.0 is the torchvision version  
# Here it is important to change the site-package folder of your virtualenv, this will take several minutes:
python3 setup.py install --user --install-lib <YOUR_PATH>/.virtualenvs/deepconsc/lib/python3.6/site-packages/
```

Please, take in account the last line of code, otherwise, it won't be possible to import torchvision from any folder.

On the other hand, there are some packages you should include in the `requirements.txt` file that are necessary by `generator.py`:
```
opencv-python
pandas
```

I will let you know more information soon, since I am still not able to reproduce `python inference.py` but I suspect that the repository is not ready to work with virtual environments.

**Comment by hdnh2006** [comment]
Ok, finally I could run the python API, doing what I commented above. The problem is the repo is not prepared for virtualenvironments. My `requirements.sh` file is like following:

```
#echo 'export OPENBLAS_CORETYPE=ARMV8' >> ~/.bashrc
#echo 'export PATH=/home/deepconsc/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/local/cuda/bin' >> ~/.bashrc
#echo 'export LD_LIBRARY_PATH=/usr/local/cuda/lib64' >> ~/.bashrc
#source ~/.bashrc
sudo apt-get install curl
sudo apt-get install wget
#sudo apt-get install python3-matplotlib
pip3 install matplotlib
#sudo apt-get install python3-pip libopenblas-dev libopenmpi-dev libomp-dev
sudo apt-get install python3-pip libopenblas-base libopenmpi-dev 

#sudo -H pip3 install future
#sudo -H pip3 install --upgrade setuptools
#sudo -H pip3 install Cython
#sudo -H pip3 install gdown

pip3 install future
pip3 install --upgrade setuptools
pip3 install Cython
pip3 install gdown

#sudo cp ~/.local/bin/gdown /usr/local/bin/gdown
#gdown https://drive.google.com/uc?id=12UiREE6-o3BthhpjQxCKLtRg3u4ssPqb
#sudo -H pip3 install torch-1.9.0a0+gitd69c22d-cp36-cp36m-linux_aarch64.whl
#rm torch-1.9.0a0+gitd69c22d-cp36-cp36m-linux_aarch64.whl
#gdown https://drive.google.com/uc?id=1tU6YlPjrP605j4z8PMnqwCSoP6sSC91Z
#sudo -H pip3 install torchvision-0.10.0a0+300a8a4-cp36-cp36m-linux_aarch64.whl
#rm torchvision-0.10.0a0+300a8a4-cp36-cp36m-linux_aarch64.whl

wget https://nvidia.box.com/shared/static/h1z9sw4bb1ybi0rm3tu8qdj8hs05ljbm.whl -O torch-1.9.0-cp36-cp36m-linux_aarch64.whl 
pip3 install numpy torch-1.9.0-cp36-cp36m-linux_aarch64.whl 

sudo apt-get install libjpeg-dev zlib1g-dev libpython3-dev libavcodec-dev libavformat-dev libswscale-dev
git clone --branch v0.10.0 https://github.com/pytorch/vision torchvision   # see below for version of torchvision to download
cd torchvision
export BUILD_VERSION=0.10.0  # where 0.x.0 is the torchvision version  
python3 setup.py install --user --install-lib /home/henry/.virtualenvs/deepconsc/lib/python3.6/site-packages/ # Here it is important to change the site-package folder of your virtualenv


pip3 install -r ../tensorrt_yolov5/requirements.txt

pip3 install seaborn --no-deps
sudo pip3 install --global-option=build_ext --global-option="-I/usr/local/cuda/include" --global-option="-L/usr/local/cuda/lib64" pycuda
wget https://github.com/ultralytics/yolov5/releases/download/v5.0/yolov5s.pt -O yolov5s.pt
#bash manage_swap.sh
```

And this is my `requirements.txt` file:
```
numpy>=1.18.5
Pillow
PyYAML>=5.3.1
scipy>=1.4.1
tqdm>=4.41.0
tensorboard>=2.4.1
thop
opencv-python
pandas
pycuda
```

I hope this can help you.
